### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by Enuvesta** [xiaoyu258/DocProj#1]
Hi!

Do you plan you open up the source code before conference?

Thanks!

**Comment by xiaoyu258** [comment]
Thanks for your attention. Yes, I will do it later.

**Comment by krishvishal** [comment]
Hi @xiaoyu258 do you have any approximate timeline? The dataset is very interesting. Would love if you can release the dataset sooner.

**Comment by xiaoyu258** [comment]
Hi, @Enuvesta @krishvishal I just upload the code and dataset. Sorry for being late.

**Comment by Enuvesta** [comment]
Thank you so much! I had a quick look on your repository and I've noticed that stiching part is done with help of .exe file. Does it mean that there is no end-to-end python pipeline for processing one input image and getting the rectified version?

**Comment by xiaoyu258** [comment]
Yes, for the stitching part I use some C++ libraries to help me implement so there is no end-to-end python pipeline currently.

**Comment by Enuvesta** [comment]
Is there any chance to see source C++ code instead od .exe file?

**Comment by krishvishal** [comment]
I think the C++ code can be made into an end-to-end pipeline with the python code using PyBind11. Hope we can see the C++ source code.

**Comment by IceSuger** [comment]
Awesome work!
Also hope to see the C++ source code of the stitching part~

**Comment by xiaoyu258** [comment]
Thanks, maybe I can try PyBind11 later. Sorry guys, for the stitching, it is a typical graph-cut problem. You can use any tools to solve them. For me, I use some internal interfaces from the company and don't have the copyright to release them.

**Comment by krishvishal** [comment]
For implementing the index optimization part the following library looks like a good candidate. 
https://github.com/amueller/gco_python.

I want to implement the stitching part in python. I'm looking for collaborators.

**Comment by NISH1001** [comment]
@xiaoyu258 Is there any way we can view the source code for stitching the flows? Or any detail description regarding the 5-dimension tensor for the unstitched flows?

**Comment by xiaoyu258** [comment]
@NISH1001 , for stitching, I use some internal interfaces from the company and don't have the copyright to release them. And you can refer to our paper for algorithm details. Sorry about that.

**Comment by NISH1001** [comment]
@xiaoyu258 Thanks. No worries.

**Comment by huxianer** [comment]
@xiaoyu258 @IceSuger Hi，Could you give me any help for  other  consistent alternative for the same function of Graph.exe?
Thank you very much for any help！

**Comment by huxianer** [comment]
@xiaoyu258 @krishvishal @IceSuge @NISH1001 @Enuvesta Hi，Could you give me any help for other consistent alternative for the same function of Graph.exe?Thank you very much for any help！
