### ISSUE TITLE
Graphcut.exe can not work.

### ISSUE THREAD

**Issue by YifeiYang210** [xiaoyu258/DocProj#10]
Excellent work for document rectification!
--------------------------------------------------------------------

But I got some problem when using the Graphcut.exe to get the stitchedFlow.npy
terminal as this:
PS D:\abpycharm\DocProj\Stitching> .\Graphcut.exe "\test data\2_patchFlows.npy" "\test data\5.npy"
\test data\2_patchFlows.npy
\test data\5.npy
flow dir: \test data\2_patchFlows.npy

But there is no 5.npy generated. I confirmed that 2_patchFlows is regulatory size as[11,8,2,256,256]
Please help me !

**Comment by xiaoyu258** [comment]
Please use the absolute path and "//" due to the path parse function in the program. e.g. H://Release//test data//2_patchFlows.npy

**Comment by Jack-Lee-NULL** [comment]
I got nothing after running Graphcut.exe, no output, no error report.
And the input of Graphcut.exe is just like C://path//... 
Please help me!

**Comment by Wanwan1996** [comment]
the same problem!! I got nothing after running Graphcut.exe, no output, no error report.
And the input of Graphcut.exe is just like C://path//...
Please help me!

**Comment by xiaoyu258** [comment]
Please use quotation marks to make sure the arguments are string type. I just download the program and this command works on my computer.

 .\Graphcut.exe 'F:\\Chrome Downloads\\Stitching\\test data\\2_patchFlows.npy' 'F:\\Chrome Downloads\\Stitching\\test data\\output.npy'
