### ISSUE TITLE
pre_trained model dont work well on your paper data

### ISSUE THREAD

**Issue by Borges-dong** [xiaoyu258/DocProj#26]
Hello! I used your geometry_model to correct distorted images. I followed your doc and tried the test_data, everything is just right.
But then I used images from your paper, it cant get the similar result. It looks like just resized it and changed little.

> **input**

![8](https://user-images.githubusercontent.com/46519438/147284198-9f2e13a6-a480-4fb8-814b-0f314069a053.jpg)

> **output**
![8_result](https://user-images.githubusercontent.com/46519438/147284216-09b75aab-2848-4b20-8a5b-3ca339c34988.png)

**Comment by SadafShafi** [comment]
I dont know why is this issue closed without being solved
I am facing the similar problems
