### ISSUE TITLE
The dataset doesn't have the original scanned image

### ISSUE THREAD

**Issue by kisstherainfh** [xiaoyu258/DocProj#4]
Hi,
when I follow your work, I find that the dataset you provide donesn't incorporate the scanned images, which are used as gorund truth to train the illumination correction network. 
Could you release this datavset

Thank you！

**Comment by xiaoyu258** [comment]
Hi @kisstherainfh, sorry for my late reply. Please check the link for the scanned images:
https://drive.google.com/open?id=1PKAtO3ml0FCXZ92j77SHtxo0XWX9QkVn

**Comment by kunlaotou** [comment]
Hi , I am lucky to find this paper and I want to train the illumination correction network to address blurred images problem in my OCR. How can I get  distorted
 training images if I get the scanned images？using resampling.rectification function？？
by the way @kisstherainfh， How does the network you train perform in real scenarios? thx！！！

**Comment by fh2019ustc** [comment]
@xiaoyu258 @kunlaotou Hi, I have not trained the illumination correction network . The question you asked is also my question. When I get a distorted crop image, how can I get the corresponding ground truth in the scanned images to train  the illumination correction network.
The model I trained performed well in real scenarios. 
I sorry for my late reply！@kunlaotou

**Comment by xiaoyu258** [comment]
For the correction network, you can use resampling.rectification function to correct the distorted image by the flow to get the input.
For the ground truth scanned image, please find the link here:
https://drive.google.com/open?id=1PKAtO3ml0FCXZ92j77SHtxo0XWX9QkVn
