### ISSUE TITLE
Stitching The Flows

### ISSUE THREAD

**Issue by NISH1001** [xiaoyu258/DocProj#5]
Hi,
I tried the stitching the tool in windows. It worked. However, I went thoroughly through the paper for how the stitching works. Can you suggest some good direction on how that can be implemented efficiently like you had the binaries in windows? This project is really intriguing. Thanks.

**Comment by xiaoyu258** [comment]
Hi @NISH1001, thanks for your interest in our work. Basically, it is a classic graph-cut problem with the objective function includes a smooth term and a data term. I think you can find some libraries to solve it, for example, you can search on Google "python graph cut" and find some related projects. To reduce the runtime, we also downsample the patch for 4x before optimization. After getting the reconstructed flow, we upsample it to the original size. I think we have mentioned it in our paper.
