### ISSUE TITLE
The link to the dataset on OneDrive is missing

### ISSUE THREAD

**Issue by GitHub920** [xiaoyu258/DocProj#6]
I can't access to that.
The message is 'This link has been removed.'
Can you restore the file? [\[OneDrive\]](https://hkustconnect-my.sharepoint.com/:f:/g/personal/xliea_connect_ust_hk/Ej_nCRH7um5Lo9SykLqD8IUBwonSuNqYjTjFp96qgqdFlA)

I am sorry but it is not allowed to use BitTorrent on my environment :(

**Comment by xiaoyu258** [comment]
I have fixed it. Please try this new link: https://hkustconnect-my.sharepoint.com/:f:/g/personal/xliea_connect_ust_hk/EsV9Q8s2g3ZNgwSYEfdnvTAB4_uIq8LEwXr1VcvaB0X8bw?e=cKtw5j
