### ISSUE TITLE
about the train dataset

### ISSUE THREAD

**Issue by diligent321** [xiaoyu258/DocProj#8]
The dewarp result in your paper is excellent. However, the links of pre-trained model and dataset are all invalid, i also try to use  Blender  to generate synthetic distorted document image, it is hard for me to master the software. so, could you please provided the dataset and pre-trained model again, very appreciated for your kindly reply !

**Comment by xiaoyu258** [comment]
Please try this new link for the dataset:
https://hkustconnect-my.sharepoint.com/:f:/g/personal/xliea_connect_ust_hk/EsV9Q8s2g3ZNgwSYEfdnvTAB4_uIq8LEwXr1VcvaB0X8bw?e=cKtw5j

**Comment by xiaoyu258** [comment]
The link for pre-trained model is valid. Can you try again?

**Comment by diligent321** [comment]
Yes, the links are all valid.
